### ISSUE TITLE
Screenshots are not embedded properly in html file

### ISSUE THREAD

**Issue by Washington3** [cucumber/cucumber-html#47] opened 2017-11-06 15:36 UTC
Hi,
Issue : In the cucumber html report file, when tapping the all the embedded screenshots are opening only the first embedded screenshot in the html file..
Issue Description:-
In a cucumber html report file, if there 3 screeshots(screenshot0.png, screenshot1.png & screenshot2.png) are embedded .. tapping screenshot1.png or screenshot2.png is opening screenshot0.png always..

Gem list:
accessible-hash (1.0.11)
actionpack (5.1.4)
actionview (5.1.4)
activesupport (5.1.4)
awesome_print (1.8.0, 1.7.0)
backports (3.10.3, 3.10.0)
better_errors (2.1.1)
bigdecimal (1.2.8)
builder (3.2.3, 3.2.2)
bundler (1.14.6, 1.13.5)
bundler-unload (1.0.2)
calabash-android (0.9.0)
calabash-cucumber (0.21.1, 0.20.0)
calabash-page-objects (0.5.6)
CFPropertyList (2.3.5, 2.3.4, 2.3.3)
clipboard (1.1.1)
coderay (1.1.2, 1.1.1)
columnize (0.9.0)
command_runner_ng (0.1.3, 0.1.2, 0.1.0)
concurrent-ruby (1.0.5)
crass (1.0.2)
cucumber (3.0.1, 3.0.0.pre.2, 1.3.19)
cucumber-core (3.0.0, 3.0.0.pre.2)
cucumber-expressions (4.0.4)
cucumber-tag_expressions (1.0.1)
cucumber-wire (0.0.1)
debase (0.2.2.beta6)
debase-ruby_core_source (0.9.2)
debugger-linecache (1.2.0)
debugger-ruby_core_source (1.3.8)
deordinalize (0.0.3)
did_you_mean (1.0.0)
diff-lcs (1.3, 1.2.5)
domain_name (0.5.20170404, 0.5.20170223, 0.5.20161129, 0.5.20160826)
edn (1.1.1)
erubi (1.7.0)
erubis (2.7.0)
escape (0.0.4)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
geocoder (1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0)
gherkin (4.1.3, 2.12.2)
http-cookie (1.0.3)
httpclient (2.8.3, 2.8.2.4)
i18n (0.9.0, 0.8.6, 0.8.1, 0.8.0, 0.7.0)
io-console (0.4.5)
json (1.8.6, 1.8.3)
loofah (2.1.1)
luffa (2.0.0)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile (0.6.0)
mini_portile2 (2.1.0)
minitest (5.8.3)
multi_json (1.12.2, 1.12.1)
multi_test (0.1.2)
net-telnet (0.1.1)
netrc (0.11.0)
nokogiri (1.6.8.1, 1.6.3.1)
parallel (1.12.0)
parallel_calabash (0.2.4)
pkg-config (1.1.7)
power_assert (0.2.6)
pretty_face (0.10.3)
pry (0.10.1)
psych (2.0.17)
rack (2.0.1)
rack-test (0.7.0)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
rake (10.4.2)
rdoc (4.2.1)
report_builder (0.1.2)
rest-client (2.0.0)
retriable (2.0.2)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
ruby-debug-ide (0.6.0)
ruby-ole (1.2.12.1, 1.2.12)
rubygems-bundler (1.4.4)
rubyzip (1.2.1, 1.2.0)
run_loop (2.6.1, 2.4.1)
rvm (1.11.3.9)
slop (3.6.0)
slowhandcuke (0.0.3)
spreadsheet (1.0.3)
syntax (1.2.2)
test-unit (3.1.5)
thor (0.20.0, 0.19.4, 0.19.1)
thread_safe (0.3.6)
tzinfo (1.2.4)
unf (0.1.4)
unf_ext (0.0.7.4, 0.0.7.3, 0.0.7.2)
yajl-ruby (1.2.1)

Highly Appreciate your prompt response.. I would be happy to share, if i missed any other details/info ..

**Comment by brasmusson** [comment] 2017-11-06 18:26
This project is not used by Cucumber-Ruby (that is the cucumber gem), so your problem is a duplicate of https://github.com/cucumber/cucumber-ruby/issues/1231, see the answer there.

**Closed by brasmusson** 2017-11-06 18:26 UTC
